### PR TITLE
GitHub authentication using OAuth token

### LINKED ISSUE #5: Support for GitHub OAuth token
Using OAuth token instead of the password is more secure in my opinion.
Details: https://developer.github.com/v3/#authentication
What do you think?

### PR DESCRIPTION
**Pull request by pyrooka**
Tested it locally, working.
Closes #5

### CODE REVIEW

**Comment by rycus86** [comment]
Awesome, thanks for this!

Unfortunately, packaging is failing on Travis (but the integration is a bit broken with this repo), see it at https://travis-ci.org/github/rycus86/release-watcher

I think this repo is half Go modules, half vendor. Can you try running `go mod vendor` (or whatever the command is) to download the new packages into the vendor directory, then commit that? Thanks!

**Comment by pyrooka** [comment]
Sorry I missed that. To be honest, I have never used vendoring in go before.

I ran the `go mod vendor` let's see what's gonna happen.

**Comment by pyrooka** [comment]
`FATA[0004] Registry push unsuccessful: response 401: 401 Unauthorized `  
Seems something is misconfigured?

**Comment by rycus86** [comment]
Nope, that's fine, I've misconfigured something, but should work from master.

**Comment by rycus86** [comment]
Thanks a lot for this again!

**Comment by pyrooka** [comment]
It is my pleasure! I am planning to make more PR-s, I hope you don't mind :)

**Comment by rycus86** [comment]
Of course, keep them coming! :D

**Pull request merged**
